neo4j:
  image: neo4j
  expose:
    - 7474
  ports:
    - "7473:7473"
  environment:
    - NEO4J_AUTH=none
app:
  build: .
  links:
    - "neo4j:neo4j"
  volumes:
    - /c/Users/y00481/_tmp/mvn/:/mvn
  command: go-wrapper run /mvn/